//Decompiles all named functions and dumps register variable instances to instances.lua.
//instances.lua is consumed by annotate_regsters.lua in CE to annotate registers at a breakpoint.
//Run from Script Manager (no cursor position required).
//Output appears in the Script Console.
//@author smc64
//@category Reversing
//@keybinding
//@menupath
//@toolbar

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.lang.Register;
import ghidra.program.model.listing.Function;
import ghidra.program.model.pcode.*;
import ghidra.program.model.symbol.SourceType;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class DumpLocals extends GhidraScript {

    private long funcEntryOffset;

    // Functions whose names contain any of these substrings are skipped.
    private static final String[] SKIP_KEYWORDS = {
        "Catch",
        "Unwind",
    };

    private static boolean shouldSkip(String name) {
        for (String kw : SKIP_KEYWORDS) {
            if (name.contains(kw)) return true;
        }
        return false;
    }

    @Override
    public void run() throws Exception {
        // Collect all named (non-auto) functions, excluding filter keywords
        List<Function> namedFuncs = new ArrayList<>();
        for (Function f : currentProgram.getFunctionManager().getFunctions(true)) {
            if (f.getSymbol().getSource() != SourceType.DEFAULT && !shouldSkip(f.getName())) {
                namedFuncs.add(f);
            }
        }
        println("Found " + namedFuncs.size() + " named functions. Decompiling...");

        File outDir;
        try {
            outDir = getSourceFile().getFile(false).getParentFile();
        } catch (Exception e) {
            outDir = new File(System.getProperty("java.io.tmpdir"));
        }
        File luaFile = new File(outDir, "out/instances.lua");

        DecompInterface decomp = new DecompInterface();
        decomp.setOptions(new DecompileOptions());
        decomp.openProgram(currentProgram);

        int done = 0, skipped = 0;
        monitor.initialize(namedFuncs.size());

        try (PrintWriter lua = new PrintWriter(luaFile)) {
            lua.println("-- Auto-generated by DumpLocals.java");
            lua.println("-- Program: " + currentProgram.getName());
            lua.println("return {");

            for (Function func : namedFuncs) {
                if (monitor.isCancelled()) break;
                monitor.setMessage(func.getName());
                monitor.incrementProgress(1);

                funcEntryOffset = func.getEntryPoint().getOffset();

                DecompileResults res = decomp.decompileFunction(func, 60, monitor);
                if (!res.decompileCompleted()) { skipped++; continue; }

                HighFunction highFunc = res.getHighFunction();
                if (highFunc == null) { skipped++; continue; }

                int n = writeInstances(lua, func, highFunc.getLocalSymbolMap());
                println(String.format("[%d/%d] %-50s %d instances",
                        ++done, namedFuncs.size(), func.getName(), n));
            }

            lua.println("}");
        } finally {
            decomp.dispose();
        }

        println("");
        println("Done. " + done + " functions written, " + skipped + " skipped.");
        println("Lua written to: " + luaFile.getAbsolutePath());
    }

    private int writeInstances(PrintWriter lua, Function func, LocalSymbolMap symMap) {
        int count = 0;
        Iterator<HighSymbol> syms = symMap.getSymbols();
        while (syms.hasNext()) {
            HighSymbol sym = syms.next();
            HighVariable var = sym.getHighVariable();
            if (var == null) continue;

            String kind = (var instanceof HighParam) ? "PARM" : "LOCL";
            String name = var.getName();
            String typeName = var.getDataType().getDisplayName();

            for (Varnode inst : var.getInstances()) {
                if (!inst.isRegister()) continue;
                Register reg = currentProgram.getLanguage()
                        .getRegister(inst.getAddress(), inst.getSize());
                if (reg == null) continue;
                long def = getDefPC(inst);
                long end = liveRangeEnd(inst);
                if (end == 0) continue; // dead / unused

                // Normalise to the largest enclosing register (e.g. EAX -> RAX)
                Register parent = reg.getParentRegister();
                String regName = (parent != null) ? parent.getName() : reg.getName();

                lua.printf("  { reg=%-6s def=0x%x, lastUse=0x%x, name=%s, type=%s, kind=%s },\n",
                        luaStr(regName) + ",",
                        def, end,
                        luaStr(name),
                        luaStr(typeName),
                        luaStr(kind));
                count++;
            }
        }
        return count;
    }

    private static String luaStr(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }

    private long getDefPC(Varnode vn) {
        Address pc = vn.getPCAddress();
        if (pc == null || pc.equals(Address.NO_ADDRESS)) return funcEntryOffset;
        return pc.getOffset();
    }

    private long liveRangeEnd(Varnode vn) {
        long end = 0;
        Iterator<PcodeOp> uses = vn.getDescendants();
        while (uses.hasNext()) {
            long addr = uses.next().getSeqnum().getTarget().getOffset();
            if (addr > end) end = addr;
        }
        return end;
    }
}
