//Exports all user-named global data symbols (non-DEFAULT, non-function) to out/globals.lua.
//Run from Script Manager (no cursor position required).
//@author smc64
//@category Reversing
//@keybinding
//@menupath
//@toolbar

import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.DataType;
import ghidra.program.model.listing.Data;
import ghidra.program.model.symbol.Symbol;
import ghidra.program.model.symbol.SymbolType;
import ghidra.program.model.symbol.SourceType;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public class DumpGlobals extends GhidraScript {

    static final long MIN_OFFSET = 0x80000000L; // Filter out small offsets that are unlikely to be real addresses

    @Override
    public void run() throws Exception {
        List<Symbol> globals = new ArrayList<>();
        for (Symbol sym : currentProgram.getSymbolTable().getAllSymbols(false)) {
            // Skip auto-named symbols
            if (sym.getSource() == SourceType.DEFAULT) continue;
            // Skip functions — those live in functions.lua
            if (sym.getSymbolType() == SymbolType.FUNCTION) continue;
            // Skip pure namespace/class containers (no meaningful address payload)
            SymbolType t = sym.getSymbolType();
            if (t == SymbolType.NAMESPACE || t == SymbolType.CLASS) continue;

            globals.add(sym);
        }
        println("Found " + globals.size() + " named global symbols.");

        File scriptDir;
        try {
            scriptDir = getSourceFile().getFile(false).getParentFile();
        } catch (Exception e) {
            scriptDir = new File(System.getProperty("java.io.tmpdir"));
        }
        File outDir = new File(scriptDir, "out");
        outDir.mkdirs();
        File luaFile = new File(outDir, "globals.lua");

        monitor.initialize(globals.size());

        String moduleName = currentProgram.getName();
        long imageBase   = currentProgram.getImageBase().getOffset();

        try (PrintWriter lua = new PrintWriter(luaFile)) {
            lua.println("-- Auto-generated by DumpGlobals.java");
            lua.println("-- Program: " + currentProgram.getName());
            lua.println("return {");

            for (Symbol sym : globals) {
                if (monitor.isCancelled()) break;
                monitor.setMessage(sym.getName());
                monitor.incrementProgress(1);

                long start = sym.getAddress().getOffset();
                if (start < MIN_OFFSET) continue; // Filter out small offsets that are unlikely to be real addresses

                Data data = currentProgram.getListing().getDataAt(sym.getAddress());
                int dataLen = (data != null && data.getLength() > 0) ? data.getLength() : 1;
                long stop = start + dataLen - 1;
                String typeName = (data != null && data.getDataType() != null)
                        ? data.getDataType().getName()
                        : sym.getSymbolType().toString();

                if (stop > start) {
                    lua.printf("  { name=%s, type=%s, start=%s, stop=%s },\n",
                            luaStr(sym.getName(true)), luaStr(typeName),
                            luaStr(moduleOffset(moduleName, imageBase, start)),
                            luaStr(moduleOffset(moduleName, imageBase, stop)));
                } else {
                    lua.printf("  { name=%s, type=%s, start=%s },\n",
                            luaStr(sym.getName(true)), luaStr(typeName),
                            luaStr(moduleOffset(moduleName, imageBase, start)));
                }
            }

            lua.println("}");
        }

        println("Done. Written to: " + luaFile.getAbsolutePath());
    }

    private static String moduleOffset(String mod, long base, long addr) {
        return mod + "+" + String.format("%X", addr - base);
    }

    private static String luaStr(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }
}
