//Exports all user-named global data symbols (non-DEFAULT, non-function) to out/globals.lua.
//Run from Script Manager (no cursor position required).
//@author smc64
//@category Reversing
//@keybinding
//@menupath
//@toolbar

import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.DataType;
import ghidra.program.model.listing.Data;
import ghidra.program.model.symbol.Symbol;
import ghidra.program.model.symbol.SymbolType;
import ghidra.program.model.symbol.SourceType;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public class DumpGlobals extends GhidraScript {

    static final long MIN_OFFSET = 0x80000000L; // Filter out small offsets that are unlikely to be real addresses

    @Override
    public void run() throws Exception {
        List<Symbol> globals = new ArrayList<>();
        for (Symbol sym : currentProgram.getSymbolTable().getAllSymbols(false)) {
            // Skip auto-named symbols
            if (sym.getSource() == SourceType.DEFAULT) continue;
            // Skip functions — those live in functions.lua
            if (sym.getSymbolType() == SymbolType.FUNCTION) continue;
            // Skip pure namespace/class containers (no meaningful address payload)
            SymbolType t = sym.getSymbolType();
            if (t == SymbolType.NAMESPACE || t == SymbolType.CLASS) continue;

            globals.add(sym);
        }
        println("Found " + globals.size() + " named global symbols.");

        File scriptDir;
        try {
            scriptDir = getSourceFile().getFile(false).getParentFile();
        } catch (Exception e) {
            scriptDir = new File(System.getProperty("java.io.tmpdir"));
        }
        File outDir = new File(scriptDir, "out");
        outDir.mkdirs();
        File luaFile = new File(outDir, "globals.lua");

        monitor.initialize(globals.size());

        try (PrintWriter lua = new PrintWriter(luaFile)) {
            lua.println("-- Auto-generated by DumpGlobals.java");
            lua.println("-- Program: " + currentProgram.getName());
            lua.println("return {");

            for (Symbol sym : globals) {
                if (monitor.isCancelled()) break;
                monitor.setMessage(sym.getName());
                monitor.incrementProgress(1);

                long offset = sym.getAddress().getOffset();
                if (offset < MIN_OFFSET) continue; // Filter out small offsets that are unlikely to be real addresses
                
                String typeName = getTypeName(sym);

                lua.printf("  { name=%s, type=%s, address=0x%x },\n",
                        luaStr(sym.getName(true)),
                        luaStr(typeName),
                        offset);
            }

            lua.println("}");
        }

        println("Done. Written to: " + luaFile.getAbsolutePath());
    }

    /** Best-effort data type name for a symbol; falls back to the symbol type name. */
    private String getTypeName(Symbol sym) {
        try {
            Data data = currentProgram.getListing().getDataAt(sym.getAddress());
            if (data != null) {
                DataType dt = data.getDataType();
                if (dt != null) return dt.getName();
            }
        } catch (Exception ignored) {}
        return sym.getSymbolType().toString();
    }

    private static String luaStr(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }
}
