//Exports all named functions with their signature and address range to out/functions.lua.
//Run from Script Manager (no cursor position required).
//@author smc64
//@category Reversing
//@keybinding
//@menupath
//@toolbar

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.AddressRange;
import ghidra.program.model.listing.Function;
import ghidra.program.model.symbol.SourceType;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public class DumpFunctions extends GhidraScript {

    @Override
    public void run() throws Exception {
        List<Function> namedFuncs = new ArrayList<>();
        for (Function f : currentProgram.getFunctionManager().getFunctions(true)) {
            if (f.getSymbol().getSource() != SourceType.DEFAULT) {
                namedFuncs.add(f);
            }
        }
        println("Found " + namedFuncs.size() + " named functions.");

        File scriptDir;
        try {
            scriptDir = getSourceFile().getFile(false).getParentFile();
        } catch (Exception e) {
            scriptDir = new File(System.getProperty("java.io.tmpdir"));
        }
        File outDir = new File(scriptDir, "out");
        outDir.mkdirs();
        File luaFile = new File(outDir, "functions.lua");

        monitor.initialize(namedFuncs.size());

        try (PrintWriter lua = new PrintWriter(luaFile)) {
            lua.println("-- Auto-generated by DumpFunctions.java");
            lua.println("-- Program: " + currentProgram.getName());
            lua.println("return {");

            for (Function func : namedFuncs) {
                if (monitor.isCancelled()) break;
                monitor.setMessage(func.getName());
                monitor.incrementProgress(1);

                String sig = func.getPrototypeString(false, false);

                // A function body may span multiple disjoint ranges (e.g. split chunks).
                for (AddressRange range : func.getBody().getAddressRanges()) {
                    lua.printf("  { name=%s, sig=%s, start=0x%x, stop=0x%x },\n",
                            luaStr(func.getName()),
                            luaStr(sig),
                            range.getMinAddress().getOffset(),
                            range.getMaxAddress().getOffset());
                }
            }

            lua.println("}");
        }

        println("Done. Written to: " + luaFile.getAbsolutePath());
    }

    private static String luaStr(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }
}
