#pragma once

#define SPARK_AXIS_PRESS_THRESHOLD 0.5f

#define SPARK_MOUSE_1 256
#define SPARK_MOUSE_2 257
#define SPARK_MOUSE_3 258
#define SPARK_MOUSE_4 259
#define SPARK_MOUSE_5 260
#define SPARK_MOUSE_6 261
#define SPARK_MOUSE_7 262
#define SPARK_MOUSE_8 263

#define SPARK_GAMEPAD_DPAD_UP 512
#define SPARK_GAMEPAD_DPAD_DOWN 513
#define SPARK_GAMEPAD_DPAD_LEFT 514
#define SPARK_GAMEPAD_DPAD_RIGHT 515
#define SPARK_GAMEPAD_START 516
#define SPARK_GAMEPAD_BACK 517
#define SPARK_GAMEPAD_LEFT_THUMB 518
#define SPARK_GAMEPAD_RIGHT_THUMB 519
#define SPARK_GAMEPAD_LEFT_SHOULDER 520
#define SPARK_GAMEPAD_RIGHT_SHOULDER 521
#define SPARK_GAMEPAD_A 524
#define SPARK_GAMEPAD_B 525
#define SPARK_GAMEPAD_X 526
#define SPARK_GAMEPAD_Y 527

// Axes: value 0-1, split into two codes for axes that go negative
#define SPARK_GAMEPAD_LEFT_TRIGGER       528  // 0-1
#define SPARK_GAMEPAD_RIGHT_TRIGGER      529  // 0-1
#define SPARK_GAMEPAD_LEFT_STICK_LEFT    530  // left  = -X
#define SPARK_GAMEPAD_LEFT_STICK_RIGHT   531  // right = +X
#define SPARK_GAMEPAD_LEFT_STICK_DOWN    532  // down  = -Y
#define SPARK_GAMEPAD_LEFT_STICK_UP      533  // up    = +Y
#define SPARK_GAMEPAD_RIGHT_STICK_LEFT   534
#define SPARK_GAMEPAD_RIGHT_STICK_RIGHT  535
#define SPARK_GAMEPAD_RIGHT_STICK_DOWN   536
#define SPARK_GAMEPAD_RIGHT_STICK_UP     537
