// #include "buildnum.h"

#define _STR(x) #x
#define STR(x) _STR(x)
#define CONCAT(x, y) x##y
#define WIDE(x) CONCAT(L,x)

#define SMC64_VERSION_MAJOR 1
#define SMC64_VERSION_MINOR 0
#define SMC64_VERSION_BUILD 0
#define SMC64_VERSION_PATCH 0

#define SMC64_VERSION_BIN SMC64_VERSION_MAJOR,SMC64_VERSION_MINOR,SMC64_VERSION_BUILD,SMC64_VERSION_PATCH

// #define __SMC64_VERSION_STRING SMC64_VERSION_MAJOR.SMC64_VERSION_MINOR.SMC64_VERSION_PATCH.SMC64_VERSION_BUILD
#define __SMC64_VERSION_STRING SMC64_VERSION_MAJOR.SMC64_VERSION_MINOR.SMC64_VERSION_BUILD.SMC64_VERSION_PATCH
#define SMC64_VERSION_STRING STR(__SMC64_VERSION_STRING)
#define SMC64_VERSION_WSTRING WIDE(SMC64_VERSION_STRING)
